-- schema.sql
-- Esquema base para Natura (PostgreSQL / Supabase)
-- Crea tablas: productos, clientes, ventas, ventaitems, cuotas, pagos

BEGIN;

-- Por claridad, apuntamos al esquema público
SET search_path TO public;

-- ======================
--   TABLA: productos
-- ======================
CREATE TABLE IF NOT EXISTS productos (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       TEXT        NOT NULL,
  detalle      TEXT,
  marca        TEXT,
  vencimiento  DATE,
  costo        NUMERIC(12,2) DEFAULT 0 CHECK (costo >= 0),
  precio       NUMERIC(12,2) DEFAULT 0 CHECK (precio >= 0),
  cantidad     INTEGER       DEFAULT 0 CHECK (cantidad >= 0)
);

-- ======================
--   TABLA: clientes
-- ======================
CREATE TABLE IF NOT EXISTS clientes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT NOT NULL,
  apellido   TEXT,
  telefono   TEXT,
  email      TEXT,
  direccion  TEXT,
  ciudad     TEXT,
  notas      TEXT
);

-- ======================
--   TABLA: ventas
-- ======================
CREATE TABLE IF NOT EXISTS ventas (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
  clienteid  BIGINT NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
  tipopago   TEXT  NOT NULL CHECK (tipopago IN ('Contado', 'Credito')),
  total      NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total  >= 0),
  saldo      NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (saldo  >= 0),
  interes    NUMERIC(5,2)  NOT NULL DEFAULT 0 CHECK (interes >= 0)
);

-- ======================
--   TABLA: ventaitems
-- ======================
CREATE TABLE IF NOT EXISTS ventaitems (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ventaid    BIGINT NOT NULL REFERENCES ventas(id)    ON DELETE CASCADE,
  productoid BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad   INTEGER       NOT NULL CHECK (cantidad > 0),
  preciounit NUMERIC(12,2) NOT NULL CHECK (preciounit >= 0)
);

-- ======================
--   TABLA: cuotas
-- ======================
CREATE TABLE IF NOT EXISTS cuotas (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ventaid  BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  nro      INTEGER NOT NULL CHECK (nro > 0),
  venceel  DATE    NOT NULL,
  monto    NUMERIC(12,2) NOT NULL CHECK (monto  >= 0),
  pagado   NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (pagado >= 0),
  saldo    NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (saldo  >= 0),
  CONSTRAINT cuotas_venta_nro_uniq UNIQUE (ventaid, nro)
);

-- ======================
--   TABLA: pagos
-- ======================
CREATE TABLE IF NOT EXISTS pagos (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ventaid  BIGINT NOT NULL REFERENCES ventas(id)  ON DELETE CASCADE,
  cuotaid  BIGINT REFERENCES cuotas(id)           ON DELETE SET NULL,
  fecha    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  monto    NUMERIC(12,2) NOT NULL CHECK (monto > 0)
);

-- ======================
--   ÍNDICES útiles
-- ======================

-- Productos
CREATE INDEX IF NOT EXISTS idx_productos_nombre      ON productos (nombre);
CREATE INDEX IF NOT EXISTS idx_productos_marca       ON productos (marca);
CREATE INDEX IF NOT EXISTS idx_productos_vencimiento ON productos (vencimiento);

-- Clientes
CREATE INDEX IF NOT EXISTS idx_clientes_apellido_nombre ON clientes (apellido, nombre);

-- Ventas
CREATE INDEX IF NOT EXISTS idx_ventas_cliente   ON ventas (clienteid);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha     ON ventas (fecha);
CREATE INDEX IF NOT EXISTS idx_ventas_tipopago  ON ventas (tipopago);

-- VentaItems
CREATE INDEX IF NOT EXISTS idx_ventaitems_venta ON ventaitems (ventaid);
CREATE INDEX IF NOT EXISTS idx_ventaitems_prod  ON ventaitems (productoid);

-- Cuotas
CREATE INDEX IF NOT EXISTS idx_cuotas_venta     ON cuotas (ventaid);
CREATE INDEX IF NOT EXISTS idx_cuotas_venceel   ON cuotas (venceel);

-- Pagos
CREATE INDEX IF NOT EXISTS idx_pagos_venta      ON pagos (ventaid);
CREATE INDEX IF NOT EXISTS idx_pagos_cuota      ON pagos (cuotaid);
CREATE INDEX IF NOT EXISTS idx_pagos_fecha      ON pagos (fecha);

-- ======================
--   (Opcional) Datos de ejemplo
--   Descomentar si querés poblar algo rápido
-- ======================
-- INSERT INTO productos (nombre, detalle, marca, vencimiento, costo, precio, cantidad)
-- VALUES
--   ('Shampoo Lumina', 'Cabello seco 300ml', 'Natura', CURRENT_DATE + 180, 3500, 5800, 12),
--   ('Crema manos', 'Ekos Castaña 75g', 'Natura', CURRENT_DATE + 365, 1800, 3200, 30);

-- INSERT INTO clientes (nombre, apellido, telefono, email, direccion, ciudad, notas)
-- VALUES
--   ('Eduardo', 'Balbastro', '037944000000', 'edu@example.com', 'San Martín 1125', 'Corrientes', NULL);

COMMIT;
